#! /bin/sh

#### AUTOSTART ####
# Set display from arandr saved script
# sh ~/.config/bspwm/monitor.sh &
autorandr --load desktop

bspc monitor DVI-D-0 -d 1 2 3 4
bspc monitor HDMI-0 -d 1 2 3 4
bspc monitor HDMI2 -d 1 2 3 4

# Notifications
/usr/bin/dunst &
nm-applet --indicator &

picom --config $HOME/.config/picom.conf &
# feh --randomize --bg-fill "/mnt/SecondSSD/Users/Jaron/MEGA/Afbeeldingen/Background/Peak Aesthetics/"* &
feh --randomize --bg-fill "/mnt/SecondSSD/Users/Jaron/MEGA/Afbeeldingen/Background/Anime/"* &
# Polkit
/usr/lib/polkit-kde-authentication-agent-1 &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sxhkd &
sudo

# Bar
sh ~/.config/polybar/launch_polybar.sh &

gap=8
PANEL_HEIGHT=25
export gap
export PANEL_HEIGHT

bspc config border_width 2
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config window_gap $gap

bspc config -m DVI-D-0 top_padding $gap
bspc config -m HDMI-0 top_padding $gap
bspc config -m HDMI2 top_padding $gap

bspc config -m DVI-D-0 bottom_padding $gap
bspc config -m HDMI-0 bottom_padding $gap
bspc config -m HDMI2 bottom_padding $gap

bspc config -m DVI-D-0 left_padding $gap
bspc config -m HDMI-0 left_padding $gap
bspc config -m HDMI2 left_padding $gap

bspc config -m DVI-D-0 right_padding $gap
bspc config -m HDMI-0 right_padding $gap
bspc config -m HDMI2 right_padding $gap

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
# fix slow resize with mouse
bspc config pointer_motion_interval 50

# ##Color settings
bspc config normal_border_color "#2f343f"
bspc config active_border_color "#424242"
bspc config focused_border_color "#96cdfb"
bspc config presel_feedback_color "#96cdfb"
bspc config urgent_border_color "#dd2727"
bspc config border_width 2

bspc rule -a yakuake state=floating
bspc rule -a systemsettings state=floating
bspc rule -a Plasma state=floating border=off
bspc rule -a plasma-desktop state=floating border=off
bspc rule -a win7 state=floating border=off
bspc rule -a krunner state=floating border=off
bspc rule -a Kmix state=floating border=off
bspc rule -a Klipper state=floating border=off
bspc rule -a Plasmoidviewer state=floating border=off
bspc rule -a firefox private=on
bspc rule -a '*:*:Picture-in-Picture' state=floating
bspc rule -a torguard state=floating
bspc rule -a TorGuard state=floating
bspc rule -a sun-awt-X11-XFramePeer state=floating

bspc rule -a Wrapper-2.0 state=floating border=off focus=on
bspc rule -a Wrapper-2.0 state=floating border=off focus=on

windowwidth=1200
windowheight=800r

screenwidth=$(xdpyinfo | awk -F'[ x]'+ '/dimensions:/{print $3}')
screenheight=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $4}')
windowx=$(("$screenwidth" / 2 - "$windowwidth" / 2))
windowy=$(("$screenheight" / 2 - "$windowheight" / 2))

bspc rule -a KeePassXC state=floating rectangle="$windowwidth"x"$windowheight"+"$windowx"+"$windowy"
bspc rule -a streamlink-twitch-gui state=floating
bspc rule -a nwjs_kjlcknihpadniagphehmpojkkdigigjp state=floating #streamlink

##  Autogap adjusts windowgap automatically according to the number of
##  windows on the desktop. Using it disables negative window gap.
#autogap &

##Edge-switcher switches to next workspace when moves moves to the
##edge of the monitor (behavior similar to enlightenment)

#edge-switcher &
#windowgrabber &

# ###External rules
# ##Pseudo automatic mode: always splits focused window when opening new window
# bspc config external_rules_command /usr/bin/pseudo_automatic_mode
# ##Adjust new window: splits biggest windows to keep windows about the same size
# #bspc config external_rules_command /usr/bin/adjust-new-window
